### ISSUE TITLE
Feature request: Enable highlighting in .mdx files

### ISSUE THREAD

**Issue by kavsingh** [bpruitt-goddard/vscode-mermaid-syntax-highlight#104]
Hi! I might be missing something here but currently, to have mermaid blocks highlighted in [`.mdx`](https://mdxjs.com/) files, I have to change file associations to read mdx as pure markdown. unfortunately this breaks all other highlighting for MDX syntax.

Would be amazing to have mermaid highlighted in MDX files. On that note would it possible to configure which file / language types this extensions works on? thanks!

**Comment by kavsingh** [comment]
Oops, answered in https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/issues/21
Closing this one, thanks!

**Comment by FilipPyrek** [comment]
Any news on this one? I would be great to have this.

My setup is [Astro Starlight](https://starlight.astro.build) which uses MDX under the hood and I added a remark plugin [remark-mermaidjs](https://www.npmjs.com/package/remark-mermaidjs). 

In VS code I use `unifiedjs.vscode-mdx` for markdown syntax highlighting.

**Comment by bpruitt-goddard** [comment]
I think mermaid support would need to be added to that other extension. If this extension were to add support for `mdx`, it would need to include highlighting for all parts of mdx (markdown in general plus jsx). I'm not aware of a way to "combine" the two extensions to have the mdx support of that extension with the subset of highlighting from this extension.

**Comment by bpruitt-goddard** [comment]
Closing this issue for now. It can be reopened if a solution or strategy can be presented to make changes here without breaking the other extension(s).
