### ISSUE TITLE
Highlighting doesn't work in <div class="mermaid"></div>

### ISSUE THREAD

**Issue by den-gr** [bpruitt-goddard/vscode-mermaid-syntax-highlight#106]
My github jekyll web site theme does not support html attributes so I can not use this syntax:

````
```mermaid {#class_context, align="center"}
classDiagram
class A
class B
A --> B
B --> C
```
```` 

But another syntax works:
```
<div id="class_context" class="mermaid">
classDiagram
class A
class B
A --> B
B --> C
</div>
```

However, with this syntax the extension highlighting doesn't work

**Comment by bpruitt-goddard** [comment]
This might have been recently fixed, can you try again. I am seeing it work properly when the file is set to markdown:
![image](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/assets/2429731/ef0e5763-9ad0-4f61-8545-76d49917a76f)
