### ISSUE TITLE
Feature Request: Include supported version of Mermaid in documentation

### ISSUE THREAD

**Issue by TonyBrookILSTU** [bpruitt-goddard/vscode-mermaid-syntax-highlight#109]
I'd like to request a small note on the VS Code "Details" page that indicates what version of Mermaid is currently supported by this plugin. 

When I visited the Mermaid homepage today to check some syntax, I found support for a couple of new experimental diagram types. These diagram types (mindmap and sankey) are not currently supported by this plugin. So I wanted to see what might be, and found the details panel lacking.

My suggestion would be to add it to the [Readme.md on line 3](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/blob/master/README.md?plain=1#L3)

Something like:

Syntax support for the [Mermaid charting language](https://github.com/knsv/mermaid). Full support for [Release 10.2.1](https://github.com/mermaid-js/mermaid/releases/tag/v10.2.1). Partial support for [Release 10.2.4](https://github.com/mermaid-js/mermaid/releases/tag/v10.2.4) - currently in development
```markdown
Syntax support for the [Mermaid charting language](https://github.com/knsv/mermaid). Full support for [Release 10.2.1](https://github.com/mermaid-js/mermaid/releases/tag/v10.2.1). Partial support for [Release 10.2.4](https://github.com/mermaid-js/mermaid/releases/tag/v10.2.4) - currently in development
```

Or, alternatively, a badge would accomplish something similar:
![Static Badge](https://img.shields.io/badge/Supported_Mermaid-12.2.1-blue)

The important part is just letting folks know what Mermaid features they can expect code highlighting with.

**Comment by bpruitt-goddard** [comment]
Unfortunately, the mermaid language moves a lot faster that my time commitments allow to maintain this package and this repo tends to fall behind. Previously, there was an area in the readme that included which diagrams were supported - maybe that should be brought back and placed near the top to make it clear? Something like (not accurate, just an example for formatting):

```md
## Supported Diagrams
- [x] Sequence Diagram
- [x] State Diagram
- [ ] Mind Map
- [ ] Quadrant Chart
```

<img width="558" alt="image" src="https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/assets/2429731/8daa67c7-5c61-4cd0-a69b-b9445eb79eaf">

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/issues/109#event-12546416385

@bpruitt-goddard, you've closed this as completed, but https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/issues/109#issuecomment-1773092194 would appear to demonstrate otherwise.

**Comment by bpruitt-goddard** [comment]
Are you suggesting that it would be helpful to bring back the list of supported diagrams? I never got any response from my comment, and we already have the screenshots/diagrams section so I figured that would be sufficient. If you disagree though, I can add the supported diagram section back.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/issues/109#issuecomment-2067771815

@bpruitt-goddard, no. I mean merely what I stated - that this was closed as complete, yet https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/issues/109#issuecomment-1773092194 appears to describe that you're unable to fulfil the request. It confused me.

**Comment by bpruitt-goddard** [comment]
Understood. In this case, I don't feel I can satisfy the initial request as outlined above. I try to keep an eye on the non-experimental diagrams that are available for the language, but I don't use many of those which makes it hard to keep fully up to date on their releases.
If there is a better suggestion for tracking diagram/version support, we can reopen and try to accommodate. But for now, I'd like to keep this comment closed to avoid too many stale issues in the repo.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/issues/109#issuecomment-2078724669

@bpruitt-goddard, maybe you could just put a "last tested" version with that disclaimer, so that a prospective user knows what version's standard features can reasonably be expected to work, but is also informed that newer features are probably supported. You could update it whenever you're satisfied that a breaking version of Mermaid's features have been tested adequately - at your own discretion.
