### ISSUE TITLE
No highlighting graph with only subgraphs

### ISSUE THREAD

**Issue by gmwxio** [bpruitt-goddard/vscode-mermaid-syntax-highlight#110]
The follow does not highlight.

~~~
```mermaid
graph
    subgraph -
        a
    end
```
~~~

Potentially it isn't 100% valid mermaid and should read `graph TB`, but it renders.

**Comment by bpruitt-goddard** [comment]
I don't believe this is technically valid syntax. The [docs](https://mermaid.js.org/syntax/flowchart.html#direction) do not define a default/unspecified orientation. I can verify that if any direction is specified it will properly highlight:

<img width="143" alt="image" src="https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/assets/2429731/aefa5a0d-2e9f-4438-a751-c2f9c1fc8cdf">
