### ISSUE TITLE
Allow .mermaid as file extension

### ISSUE THREAD

**Issue by henrikrxn** [bpruitt-goddard/vscode-mermaid-syntax-highlight#111]
According to the Mermaid documentation .mermaid is also a file extension for mermaid files

https://mermaid.js.org/ecosystem/integrations.html#file-extension

**Comment by bpruitt-goddard** [comment]
This should already be working as a file extension. The files [in the tests directory](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/tree/master/tests/diagrams) are all using the `.mermaid` extension and are properly highlighting.
