### ISSUE TITLE
[Meta] Enable GitHub Discussions.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [bpruitt-goddard/vscode-mermaid-syntax-highlight#126]
My rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245. However, specifically here, I would like to ask whether nested HTML and Markdown are correctly rendered (https://mermaid.js.org/syntax/flowchart.html#markdown-formatting versus https://mermaid.js.org/syntax/flowchart.html#unicode-text, the latter supporting HTML).

For instance:

~~~.MD
```mermaid
flowchart TD
	node_s9gvm9["`
		**Heading**
		Body text.
	`"]
	node_s9gyel["
		<b>Heading</b>
		Body text.
	"]
```
~~~

**Comment by bpruitt-goddard** [comment]
I enabled discussions on the repo, feel free to post your question over there and close this issue. Thanks for the suggestion!
