### ISSUE TITLE
Casing for "note" keyword

### ISSUE THREAD

**Issue by johnfrings** [bpruitt-goddard/vscode-mermaid-syntax-highlight#131]
The "Note" keyword in sequence diagrams strictly matches "Note" with a capital "N". The documentation does refer the the keyword using a capital "N" but the renderer happily accepts "note" with a lowercase "n". Therefore I think the syntax highlighting should accept the lowercase variant of the "note" keyword.

**Comment by bpruitt-goddard** [comment]
This has been fixed in the newly published version 1.6.4:

![image](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/assets/2429731/fb1f3598-8b8b-4d4a-ac4b-88b6fe0e1f17)
