### ISSUE TITLE
Support Entity Name Aliases (v10.5.0+) in ER diagram

### ISSUE THREAD

**Issue by Nobuho** [bpruitt-goddard/vscode-mermaid-syntax-highlight#142]
Thank you for the great add-on. I would like to make a request for improvement.
Could you please support Entity Name Aliases (v10.5.0+) in ER diagram? Thank you.

Mermaid.org：
https://mermaid.js.org/syntax/entityRelationshipDiagram.html?_sm_au_=iVVJFmNst0H0WZq3jCptWK7c0B0JC#entity-name-aliases-v10-5-0

Mermaid Example：
```
erDiagram
    p[Person] {
        string firstName
        string lastName
    }
    a["Customer Account"] {
        string email
    }
    p ||--o| a : has
```

Current syntax highlights：
![image](https://github.com/user-attachments/assets/577d1409-f555-4bab-a4aa-e9e4fc2a7ac7)

**Comment by bpruitt-goddard** [comment]
This is fixed in the latest version 1.6.7:

![image](https://github.com/user-attachments/assets/e78fefed-96a4-40d0-85f0-4e22296a2aaf)
