### ISSUE TITLE
fontawsome icon work in preview but is not shown when generating an image.

### ISSUE THREAD

**Issue by alanlivio** [bpruitt-goddard/vscode-mermaid-syntax-highlight#143]
For instance, this [basic example from the mermaid documentation](https://mermaid.js.org/syntax/flowchart.html#basic-support-for-fontawesome) is not shown when generating an image.
```
flowchart TD
    B["fa:fa-twitter for peace"]
    B-->C[fa:fa-ban forbidden]
    B-->D(fa:fa-spinner)
    B-->E(A fa:fa-camera-retro perhaps?)
```

**Comment by bpruitt-goddard** [comment]
This repo/extension is only for the syntax highlighting, which appears to be working:
![image](https://github.com/user-attachments/assets/acb175f4-e969-42b5-9ae5-223ad552c8ce)

You might be looking for a different repo/extension that is rendering the image. Perhaps [Mermaid Preview](https://github.com/Mermaid-Chart/vscode-mermaid-preview)?

**Comment by alanlivio** [comment]
You are right. Thank you
