### ISSUE TITLE
Broken highlight when node text contains HTML tags

### ISSUE THREAD

**Issue by vstirbu** [bpruitt-goddard/vscode-mermaid-syntax-highlight#17]
The highlight is broken then the text contains HTML tags like `<br>`. The following example:

```mermaid
graph LR
  working(highlight works)
  broken("broken <br> highlight")
  broken(broken <br> highlight)
```

yields this result:

<img width="398" alt="screenshot 2019-02-27 at 23 44 42" src="https://user-images.githubusercontent.com/1288047/53525076-ab76ee80-3ae9-11e9-8a2a-44fe830d8e6e.png">

Plugin version: 1.0.0

**Comment by bpruitt-goddard** [comment]
I can see a few ways to handle this:

1. Highlight like the rest of the text
1. Highlight in proper HTML syntax highlighting
1. A new mermaid-specific HTML highlighting?

(1) should be easy to do. I don't see (2) being needed unless there is a lot of HTML being written, which I'm assuming doesn't normally happen (correct me if I'm wrong)?

**Comment by vstirbu** [comment]
Option 1 should be enough for my needs. I use `<br>` to break long lines.

**Comment by bpruitt-goddard** [comment]
Awesome! I fixed this in the associated PR. 

I pushed out version 1.0.1 of the extension so you should be able to update shortly and see the fixes for both of your bugs. Thanks for the code and screenshots - it made fixing it really easy!
