### ISSUE TITLE
Punctuation marks break graph highlighting

### ISSUE THREAD

**Issue by vstirbu** [bpruitt-goddard/vscode-mermaid-syntax-highlight#18]
Using punctuation marks `.`, `,`, `!`, `?` in node's text in graph diagrams disables highlighting:

```mermaid
graph LR
  box[New commit.]
  circle((dsfhkdhfkjsd,))
  rounded(dkfhkdshkfs?)
  decision{gsjhgjs!}
```

produces this result:

<img width="312" alt="screenshot 2019-02-27 at 23 56 05" src="https://user-images.githubusercontent.com/1288047/53525784-41f7df80-3aeb-11e9-9c0c-107db33dd7a8.png">

Plugin version: 1.0.0

**Comment by bpruitt-goddard** [comment]
Fixed wit the associated PR. I added a few other puncuations as well. I'll push the fix up for this after taking a look at the other issue.

![image](https://user-images.githubusercontent.com/2429731/53530440-b4919c80-3aa4-11e9-965f-46ec1b46ef7a.png)
