### ISSUE TITLE
Support for classDiagram and gitGraph

### ISSUE THREAD

**Issue by ppeters917** [bpruitt-goddard/vscode-mermaid-syntax-highlight#25]
Please add syntax highlight to classDiagramm and gitGraph

**Comment by ricardorauber-poatek** [comment]
+1

**Comment by bpruitt-goddard** [comment]
`classDiagram` support has been added. 

`gitGraph` is still marked as experimental. Any idea on whether it will come out of this state soon? I build the highlighting based off the examples [here](https://mermaid-js.github.io/mermaid/#/?id=git-graph-exclamation-experimental). As it is experimental, the documentation isn't very thorough so there might be some cases missed.

**Comment by bpruitt-goddard** [comment]
I noticed that `gitGraph` is no longer tagged experimental, so support has been added.
