### ISSUE TITLE
Broken highlighting in sequence diagram with newline

### ISSUE THREAD

**Issue by gtaylor1981** [bpruitt-goddard/vscode-mermaid-syntax-highlight#30]
Highlighting is broken in sequence diagrams when a participant's label contains `<br>`. Example:

```mermaid
sequenceDiagram
    participant T as Highlighting<br/>broken
    Note over T: Highlighting<br/>working
```

Result:
![image](https://user-images.githubusercontent.com/20638908/85832554-9e771780-b790-11ea-8efd-4183018bae78.png)

Perhaps the `<br/>` tag could have highlighting in a different colour to the text, here's an example I made in Paint:

![image](https://user-images.githubusercontent.com/20638908/85832829-12b1bb00-b791-11ea-8476-0ab67e8cce3b.png)

Seen in v1.0.2

**Comment by bpruitt-goddard** [comment]
Thanks for reporting! I fixed the highlighting to match the `Note` line in your screenshot and released a new version with the fix. I'll hold off on highlighting tags in different colors as that could get complex and it would be best to do it across all diagrams/text.
