### ISSUE TITLE
Add support for Azure DevOps wiki weird mermaid syntax

### ISSUE THREAD

**Issue by pburrows** [bpruitt-goddard/vscode-mermaid-syntax-highlight#32]
AzDo Wiki uses a [weird syntax](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-mermaid-diagrams-to-a-wiki-page) for marking the start/end of a mermaid block. 

Essentially, the blocks are delimitted with colons (:) instead of back-ticks Like this:

    ::: mermaid
    graph LR
      A --> B
    :::

Any chance support for this syntax can be added to this plugin?

**Comment by bpruitt-goddard** [comment]
@pburrows Apologies for the delay. Taking a look at this, I notice that there is no built in support in VS Code's markdown for colon-delimited code blocks. Are you using any plugin that supports other languages in those style of code blocks? I'm trying to determine whether I'd need to define these code blocks myself or if other plugins provide some support I can leverage.

**Comment by tallguyjenks** [comment]
just came here to file the same issue. Would also find it valuable for me and my team while writing docs to see the highlighting with the colon syntax. 

> thanks microsoft for breaking spec -__-

**Comment by bpruitt-goddard** [comment]
This was fixed in version 1.2.4 🚀. It required implementing custom regex to support the weird syntax as there doesn't appear to be an easy way for VS Code to recognize the syntax.
