### ISSUE TITLE
Syntax not displayed as expected

### ISSUE THREAD

**Issue by sweihub** [bpruitt-goddard/vscode-mermaid-syntax-highlight#38]
Hi, thanks for the plugin, it really helps a lot, but I found the issue, the syntax was not correctly displayed,  the node caption was not colored as expected,  what's the problem? I am using the latest VSCode, thank you!

![image](https://user-images.githubusercontent.com/5334841/102049147-51a8fb00-3e1b-11eb-8039-0fe6dc0ad85f.png)

![image](https://user-images.githubusercontent.com/5334841/102049260-85842080-3e1b-11eb-8cfd-9698f48ee070.png)

**Comment by TimothyHills** [comment]
I'm having the same issue.
![mermaid](https://user-images.githubusercontent.com/8600409/122562942-894b6680-d03b-11eb-83ec-79fa813d84ce.png)

**Comment by bpruitt-goddard** [comment]
With the changes from the linked PR adding some missing entity links, I'm seeing the appropriate syntax. 
<img width="461" alt="image" src="https://user-images.githubusercontent.com/2429731/184623548-2c5cfe79-8f27-4b1d-b8ce-f06f2565b956.png">


From the second comment, note at the beginning of the fourth line, there is a small spacing issue that is causing the arrow head link to not be rendered (`-->|`):
<img width="585" alt="image" src="https://user-images.githubusercontent.com/2429731/184622248-0e813cb1-c696-439a-bde9-c60f8116998d.png">
