### ISSUE TITLE
The extension should have a logo

### ISSUE THREAD

**Issue by vitaliy-guliy** [bpruitt-goddard/vscode-mermaid-syntax-highlight#45]
This extension become a pretty popular. It has 61315 of downloads. This is almost half of downloads that Markdown Preview Mermaid Support has. It's a good progress!!

I think it's time to find a dedicated icon for the extension.

We are trying to introduce this extension to our [Eclipse Che](https://www.eclipse.org/che).
Since there is no icon, the default one is used

![Screenshot from 2021-02-23 19-59-26](https://user-images.githubusercontent.com/1655894/108886632-dda48380-7611-11eb-80bc-da1322855798.png)

**Comment by bpruitt-goddard** [comment]
@vitaliy-guliy  Do you have any recommendations? I have no artistic/design skills 😆 .

**Comment by vitaliy-guliy** [comment]
I will say if I invent something :-)

**Comment by git-benjamin** [comment]
@bpruitt-goddard [Pull request for icon created using royalty and attribution free images.
](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/pull/94)

**Comment by bpruitt-goddard** [comment]
Fixed with #94
