### ISSUE TITLE
Please add the extension to open-vsx.org

### ISSUE THREAD

**Issue by lduktus** [bpruitt-goddard/vscode-mermaid-syntax-highlight#46]
It would make it more accessible for people using VSCodium and other editors.
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by bpruitt-goddard** [comment]
Closing this issue as it appears that at some point open-vsx started getting the VS Code extensions automatically. [This open-vsx extension link](https://open-vsx.org/extension/bpruitt-goddard/mermaid-markdown-syntax-highlighting) shows the extension with its latest version.
