### ISSUE TITLE
syntax error when add note to statediagram

### ISSUE THREAD

**Issue by heartacker** [bpruitt-goddard/vscode-mermaid-syntax-highlight#55]
```mermaid
stateDiagram-v2


state github_gitlab{
Local0-->git_Server:push
git_Server-->Local0:pull
}
note left of github_gitlab: 最常见\n 的方式
state gerrit{
gerrit_server-->git_server:commit
Local1-->gerrit_server:push with review
git_server-->Local1:pull/sync
}


```

![image](https://user-images.githubusercontent.com/1876302/122872268-cd53a980-d362-11eb-913d-8fb3b8a572ed.png)

**Comment by heartacker** [comment]
hi,anybody could fix this?

**Comment by bpruitt-goddard** [comment]
I see two bugs needed to fix this:
1. No space before the colon on the line
2. The `\` backslash character not being escaped for the note text

I'll work on these fixes, but in the meantime, there is this workaround: add a space before the colon. This will not fix the highlighting after the backslash, but will allow the highlighting to continue working on the rest of the diagram:

`note left of github_gitlab : 最常见\n 的方式`

![image](https://user-images.githubusercontent.com/2429731/123820537-82301e00-d8af-11eb-95b5-39bcc92ce4b8.png)

Additionally, you'll see more syntax highlighting work by adding spacing around the arrows/curly brackets. I think changing the spacing to be optional globally will be a larger work item:

```mermaid
stateDiagram-v2


  state github_gitlab {
  Local0 --> git_Server:push
  git_Server --> Local0:pull
  }
  note left of github_gitlab : 最常见\n 的方式
  state gerrit {
    gerrit_server --> git_server:commit
    Local1 --> gerrit_server:push with review
    git_server --> Local1:pull/sync
  }

```

![image](https://user-images.githubusercontent.com/2429731/123821076-f23ea400-d8af-11eb-8e78-37d15b96b6ac.png)

**Comment by bpruitt-goddard** [comment]
This will go out with the next release (1.4.2). With the fix I'm seeing the diagram highlight properly:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/2429731/185760081-da248504-5f67-43ee-bf76-9634e79e3815.png">
