### ISSUE TITLE
Which ligatures font are you using?

### ISSUE THREAD

**Issue by Krebrov001** [bpruitt-goddard/vscode-mermaid-syntax-highlight#59]
I noticed that in the screenshots you are using a font with ligatures.

<img src="https://raw.githubusercontent.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/master/images/classDiagram.png" alt="Class Diagram Screenshot" width="500">

Can you specify which font is that?

**Comment by bpruitt-goddard** [comment]
It is the [JetBrains Mono Font](https://www.jetbrains.com/lp/mono/), with the setting `"editor.fontLigatures": true` for the ligatures.
