### ISSUE TITLE
Flowchart nodes with only an Id are not highlighted with node color

### ISSUE THREAD

**Issue by ANHPearce** [bpruitt-goddard/vscode-mermaid-syntax-highlight#62]
flowchart LR
    thisWillNotbeHighlighted

flowchart LR
    this[WillbeHighlighted]
    
   Seems like you pattern is matching on the optional "node with text", i.e. id[ ] , pattern.

**Comment by bpruitt-goddard** [comment]
Fixed in #65 and pushed out with version 1.2.3.
