### ISSUE TITLE
Multiline text doesn't highlighted

### ISSUE THREAD

**Issue by dormeiri** [bpruitt-goddard/vscode-mermaid-syntax-highlight#64]
### Diagram

```mermaid
flowchart TB
    A["
        Multiline
        text
        1
    "]
    B[Multiline\ntext\n2]
```

### Actual highlight

![image](https://user-images.githubusercontent.com/37194716/154704271-9bfe85bd-a23a-45c5-beb9-c32f978b6b69.png)

### Expected

The text of the shape A should be highlighted

**Comment by bpruitt-goddard** [comment]
This was a bit trickier than I had expected and required a bit of refactoring. But it is fixed in version **1.4.2** 🎉 :

<img width="300" alt="image" src="https://user-images.githubusercontent.com/2429731/195818799-cf45f1d9-a88e-4bee-bf99-87aa156c2ce0.png">
