### ISSUE TITLE
In classDiagram, add reversed arrows *-- and o--

### ISSUE THREAD

**Issue by dtyeos** [bpruitt-goddard/vscode-mermaid-syntax-highlight#68]
These two arrows are valid mermaid syntax but are not correctly highlighted in VSCode 1.68.0.
![image](https://user-images.githubusercontent.com/107921024/174767327-3d7f73c8-1e36-44f1-8777-72fb78c45f0f.png)

**Comment by bpruitt-goddard** [comment]
Fixed, see the updated example screenshot, lines ~5-6

<img src="https://raw.githubusercontent.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/master/images/classDiagram.png" alt="Class Diagram Screenshot" width="500">
