### ISSUE TITLE
title keyword is not highlighted/recognised

### ISSUE THREAD

**Issue by basvdijk** [bpruitt-goddard/vscode-mermaid-syntax-highlight#76]
When using the `title` keyword it is not highlighted

![image](https://user-images.githubusercontent.com/644550/181441099-322a5aa2-16c6-4b32-ad18-80f943b1a48f.png)

While the code renders fine
```
sequenceDiagram
    autonumber
    participant APP as APP
    participant BE as Backend

    title Test diagram
```

into:
```mermaid
sequenceDiagram
    autonumber
    participant APP as APP
    participant BE as Backend

    title Test diagram
```

**Comment by bpruitt-goddard** [comment]
Fixed in `1.3.4`
<img width="350" alt="image" src="https://user-images.githubusercontent.com/2429731/183342655-81edbf1e-6c80-458c-8a8b-52631b400e92.png">
