### ISSUE TITLE
No highlight within the order

### ISSUE THREAD

**Issue by freshchild** [bpruitt-goddard/vscode-mermaid-syntax-highlight#86]
Like this:

![image](https://user-images.githubusercontent.com/31954237/188296316-11bc5a84-c88b-4e02-ab30-5a544909725a.png)

Text (added a % in line 4):

```txt
```mermaid
flowchart LR
    id1([":)"])
%```

1. test

    ```cpp
    #include <complex>
    ```

    ```cpp
    #include <complex>
    ```

    ```mermaid
    flowchart LR
        id1([":("])
    ```

    ```cpp
    #include <complex>
    ```
```

**Comment by piranna** [comment]
Same issue here. How can we help on this?

**Comment by bpruitt-goddard** [comment]
I'm not sure which fix solved this, but I'm seeing it work properly now. Both mermaid and C++ are rendering their syntax highlighting: 

<img width="260" alt="image" src="https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/assets/2429731/27f2b954-d8a6-4576-a3d7-e04071626da9">
