### ISSUE TITLE
Syntax highlight leaking from code blocks to markdown text

### ISSUE THREAD

**Issue by jikuja** [bpruitt-goddard/vscode-mermaid-syntax-highlight#87]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/928458/191854902-51d073b6-0111-4c62-82cf-f9d54c198adb.png">

**Comment by bpruitt-goddard** [comment]
I confirmed this does not happen with non-ADO code blocks:

![markdown multiple test](https://user-images.githubusercontent.com/2429731/215870969-5171e7ac-22d8-4dc3-b411-eca240590403.jpg)

The linked PR fixes the problem and adds a test to verify going forward.
