### ISSUE TITLE
Using html tags in text on links breaks the syntax highlighting

### ISSUE THREAD

**Issue by dongwook-chan** [bpruitt-goddard/vscode-mermaid-syntax-highlight#98]
Adding html tags on links breaks the following markdown syntax highlighting.

```bash
graph TB;
    A--a-->B
    B--"<b>[b]</b>\nb"-->C
```

### Before adding mermaid
![image](https://user-images.githubusercontent.com/29939301/219944706-93485e27-5141-4d58-839b-ab36ae3f6c9e.png)

### After adding mermaid
![image](https://user-images.githubusercontent.com/29939301/219944690-c10cb164-3214-4206-bd0f-d8188b67788b.png)

**Comment by tymokvo** [comment]
I think I am experiencing this same issue, but it seems to be with strings that match the regex:
`(?<=\w)>`

Highlighting broken:
![image](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/assets/12144028/8575cbaf-e441-4f7c-9512-a083c6a81410)


Highlighting correct:
![image](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/assets/12144028/cc530514-bb9f-4b2d-9ce7-c75d3df4c393)


![image](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/assets/12144028/08bb0741-4632-47f8-85e8-d138dd9b9c56)

![image](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/assets/12144028/d40c54cf-07a6-4bcb-a3a4-07a3ecc414b3)

**Comment by bpruitt-goddard** [comment]
Fixed with the linked PR and deployed with version 1.6.1.
